// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6N4QqhaZVPcAYp1kG1hJ-0vxG1KwI0Q',
    appId: '1:348645878864:web:1fd94c5bd169b066b77555',
    messagingSenderId: '348645878864',
    projectId: 'flutterauth-2a014',
    authDomain: 'flutterauth-2a014.firebaseapp.com',
    storageBucket: 'flutterauth-2a014.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaEUAPuYmPRPWnOLcUUPcBXP2sPm9_XW8',
    appId: '1:348645878864:android:4f682de7caebebbfb77555',
    messagingSenderId: '348645878864',
    projectId: 'flutterauth-2a014',
    storageBucket: 'flutterauth-2a014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx7wUqNl_dSMh25o9y4eSzH2SiNb3QF5I',
    appId: '1:348645878864:ios:ba877c334a0caf5bb77555',
    messagingSenderId: '348645878864',
    projectId: 'flutterauth-2a014',
    storageBucket: 'flutterauth-2a014.appspot.com',
    iosBundleId: 'com.example.halo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx7wUqNl_dSMh25o9y4eSzH2SiNb3QF5I',
    appId: '1:348645878864:ios:89099ff7fda49d02b77555',
    messagingSenderId: '348645878864',
    projectId: 'flutterauth-2a014',
    storageBucket: 'flutterauth-2a014.appspot.com',
    iosBundleId: 'com.example.halo.RunnerTests',
  );
}
